version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1917
      POSTGRES_DB: demo
    volumes:
      - ./postgres-backup:/postgres-backup
    ports:
      - 5432:5432
